function _nfMealTypes(){return ['Desayuno','Almuerzo','Merienda','Cena','Snack']}
function _nfFoodCategories(){return typeof foodCategories==='function'?foodCategories():[]}
function _nfFoodList(query='',category=''){return typeof searchFoods==='function'?searchFoods(query,category):Object.keys(allFoods()).filter(n=>!query||n.toLowerCase().includes(String(query).toLowerCase())).slice(0,80)}
function _nfFoodLabel(name){return `${foodIcon(name,allFoods()[name])} ${name}`}
const MEAL_ROLES=['principal','guarnicion','extra'];
const MEAL_ROLE_LABELS={principal:'Principal',guarnicion:'Guarnición',extra:'Extra'};
function createMealDraft(type){return {type:_nfMealTypes().includes(type)?type:'Snack',items:[],activeRole:'principal'}}
function normalizeMealRole(role){return MEAL_ROLES.includes(role)?role:'principal'}
function addMealDraftItem(draft,item,role){if(!draft||!item)return draft;draft.items.push({...item,mealRole:normalizeMealRole(role||draft.activeRole)});return draft}
function removeMealDraftItem(draft,index){if(!draft||!Number.isInteger(index)||index<0||index>=draft.items.length)return draft;draft.items.splice(index,1);return draft}
function updateMealDraftItem(draft,index,patch){if(!draft||!Number.isInteger(index)||index<0||index>=draft.items.length)return draft;draft.items[index]={...draft.items[index],...(patch||{}),mealRole:normalizeMealRole(patch?.mealRole||draft.items[index].mealRole)};return draft}
function mealDraftByRole(draft,role){const r=normalizeMealRole(role);return (draft?.items||[]).filter(x=>normalizeMealRole(x.mealRole)===r)}
function mealDraftRoleSections(draft){return Object.fromEntries(MEAL_ROLES.map(r=>[r,mealDraftByRole(draft,r)]))}
function mealDraftTotals(draft){const keys=['kcal','p','c','f','fib','sugar','sat','sodium'];const out=Object.fromEntries(keys.map(k=>[k,0]));(draft?.items||[]).forEach(x=>keys.forEach(k=>{const v=Number(x[k]);if(Number.isFinite(v))out[k]+=v}));return out}
function groupMealEntries(entries){const out=Object.fromEntries(_nfMealTypes().map(t=>[t,[]]));(entries||[]).forEach(x=>{const t=_nfMealTypes().includes(x.type)?x.type:'Snack';out[t].push(x)});return out}
function _nfFmt(n){return Number.isFinite(Number(n))?Math.round(Number(n)):0}
function _nfDraftItemHtml(item,i){const role=normalizeMealRole(item.mealRole);return `<div class="nf-meal-draft-item"><div><span class="nf-role-badge">${MEAL_ROLE_LABELS[role]}</span><br><b>${esc(foodIcon(item.food,allFoods()[item.food]))} ${esc(item.food)}</b><br><small>${esc(item.amount)} ${esc(item.unit||item.inputUnit||'g')}</small></div><div class="nf-draft-item-right"><b>${_nfFmt(item.kcal)} kcal</b><div><button class="secondary small" type="button" onclick="editMealDraftItemUI(${i})">Editar</button><button class="secondary small" type="button" onclick="removeMealDraftItemUI(${i})">Eliminar</button></div></div></div>`}
function renderMealComposer(){
 const draft=window._nfMealDraft;if(!draft)return;
 const types=_nfMealTypes(),fs=allFoods(),recent=recentFoods(getActiveProfile().id,6),favs=(db.favoriteFoods||[]).filter(x=>x.pid===getActiveProfile().id).map(x=>x.food).filter(n=>fs[n]),cats=_nfFoodCategories();
 const selected=window._selectedFoodName||'';
 const catHtml=cats.map(c=>`<button class="nf-food-category" type="button" data-category="${esc(c.id)}" onclick="setFoodCategory('${esc(c.id)}')">${esc(c.label)}</button>`).join('');
 const roleSections=mealDraftRoleSections(draft);
 const list=draft.items.map(_nfDraftItemHtml).join('');
 const roleSectionHtml=MEAL_ROLES.map(r=>`<section class="nf-meal-role-section ${draft.activeRole===r?'active':''}"><div class="nf-meal-role-heading"><div><b>${MEAL_ROLE_LABELS[r]}</b><small>${roleSections[r].length?`${roleSections[r].length} alimento${roleSections[r].length===1?'':'s'}`:'Sin agregar'}</small></div><button class="secondary small" type="button" onclick="beginMealRoleAdd('${r}')">＋ Agregar</button></div>${roleSections[r].length?`<div class="nf-meal-draft-list">${roleSections[r].map(item=>_nfDraftItemHtml(item,draft.items.indexOf(item))).join('')}</div>`:`<div class="nf-role-empty">Tocá «Agregar» para sumar un alimento.</div>`}</section>`).join('');
 const t=mealDraftTotals(draft);
 const composer=`<div class="meal-modal">
   <div class="nf-meal-composer-title"><b>${esc(draft.type)}</b><span>${draft.items.length?`${draft.items.length} alimento${draft.items.length===1?'':'s'}`:'Todavía no agregaste alimentos'}</span></div>
   <div class="nf-role-picker"><span>Componente:</span>${MEAL_ROLES.map(r=>`<button class="nf-role-btn ${draft.activeRole===r?'active':''}" type="button" onclick="beginMealRoleAdd('${r}')">${MEAL_ROLE_LABELS[r]}</button>`).join('')}</div>
   <div class="nf-meal-role-sections">${roleSectionHtml}</div>
   <label class="modal-label">¿Qué comiste?</label>
   <div class="search-wrap"><input id="foodSearch" type="search" placeholder="🔍 Buscar alimento..." autocomplete="off" oninput="filterFoodPicker()" ${selected?'readonly':''} value="${esc(selected)}"></div>
   <div id="searchResults" class="search-results"></div>
   <div id="selectedFood" class="selected-food ${selected?'':'hidden'}"><div id="selectedFoodName" class="selected-name">${esc(selected)}</div>
     <div class="food-form"><div class="unitrow"><div><label>Cantidad</label><input id="qty" type="number" min="0.25" step="1" placeholder="Ingresá la cantidad"></div><div><label>Unidad</label><select id="qtyUnit" onchange="updateMealUnitUI()"></select></div></div>
       <div class="modal-actions"><button class="secondary small" type="button" onclick="toggleFavoriteSelected()">⭐ Favorito</button><button class="btn-primary" type="button" onclick="addMealDraftItemUI()">＋ Agregar al ${esc(draft.type.toLowerCase())}</button></div>
     </div>
   </div>
   ${draft.items.length?`<button class="btn-primary nf-save-meal nf-save-meal-top" type="button" onclick="saveMealDraft()">Guardar ${esc(draft.type.toLowerCase())}</button>`:''}
   <div id="foodCategoryNav" class="chip-section"><span class="chiptitle">Categorías</span><div class="cat-grid">${catHtml}</div></div>
   <div id="foodQuickSection">${favs.length?`<div class="chip-section"><span class="chiptitle">⭐ Favoritos</span><div class="chip-row">${favs.map(n=>`<button class="chip" type="button" onclick="pickFoodQuick('${encodeURIComponent(n)}')">${esc(n)}</button>`).join('')}</div></div>`:''}${recent.length?`<div class="chip-section"><span class="chiptitle">🕒 Recientes</span><div class="chip-row">${recent.map(n=>`<button class="chip" type="button" onclick="pickFoodQuick('${encodeURIComponent(n)}')">${esc(n)}</button>`).join('')}</div></div>`:''}<button class="chip add-custom" type="button" onclick="newCustomFood()">＋ Agregar alimento personalizado</button></div>
   ${draft.items.length?`<div class="nf-meal-total"><div><b>Total del ${esc(draft.type.toLowerCase())}</b><strong>${_nfFmt(t.kcal)} kcal</strong></div><div class="nf-meal-total-macros"><span>Proteína <b>${_nfFmt(t.p)} g</b></span><span>Carbohidratos <b>${_nfFmt(t.c)} g</b></span><span>Grasas <b>${_nfFmt(t.f)} g</b></span><span>Fibra <b>${_nfFmt(t.fib)} g</b></span></div></div>`:''}
 </div>`;
 openModal({title:'🍽️ Registrar comida',body:composer});
 window._nfFoodCategory=window._nfFoodCategory||'';
 filterFoodPicker();
 if(selected)updateMealUnitUI(false);
}
function addMeal(preselect=''){
 const types=_nfMealTypes(),forcedType=types.includes(preselect)?preselect:'',foodPreselect=forcedType?'':preselect,p=getActiveProfile();if(!p)return;
 window._nfMealDraft=createMealDraft(forcedType||inferMealType());window._selectedFoodName='';window._nfFoodCategory='';renderMealComposer();if(foodPreselect&&allFoods()[foodPreselect])selectFood(foodPreselect);
}
function filterFoodPicker(){const q=document.getElementById('foodSearch')?.value||'',cat=window._nfFoodCategory||'',el=document.getElementById('searchResults'),quick=document.getElementById('foodQuickSection');if(!el)return;if(window._selectedFoodName){el.innerHTML='';el.classList.add('hidden');if(quick)quick.classList.add('hidden');return}const list=_nfFoodList(q,cat);if(!q&&!cat){el.innerHTML='';el.classList.add('hidden');if(quick)quick.classList.remove('hidden');if(window._nfFoodPreselect){const name=window._nfFoodPreselect;window._nfFoodPreselect='';if(allFoods()[name])selectFood(name)}return;}if(quick)quick.classList.add('hidden');el.classList.remove('hidden');if(!list.length){el.innerHTML=`<div class="no-results">No encontré ese alimento.<br><button class="chip add-custom" type="button" onclick="newCustomFood()">＋ Agregar alimento personalizado</button></div>`;return}let html='';let lastGroup='';let lastSub='';list.forEach(n=>{const f=allFoods()[n];if(cat==='carnes-proteinas'&&typeof foodProteinGroups==='function'){const g=(foodProteinGroups(n)[0]||'Otros');if(g!==lastGroup){html+=`<div class="nf-protein-group">${esc(g)}</div>`;lastGroup=g}}if(cat==='comidas-preparadas'){const sub=f?.subcategory==='postres'?'postres':'platos';if(sub!==lastSub){html+=`<div class="nf-protein-group nf-food-subcategory">${sub==='postres'?'🍨 Postres':'🍽️ Platos preparados'}</div>`;lastSub=sub}}html+=`<button class="food-result" type="button" onclick="selectFood('${encodeURIComponent(n)}')"><span class="food-result-name">${esc(foodIcon(n,f))} ${esc(n)}</span><span class="food-result-kcal">${Math.round(f?.kcal||0)} kcal</span></button>`});el.innerHTML=html}
function setFoodCategory(category){window._nfFoodCategory=String(category||'');document.querySelectorAll('.nf-food-category').forEach(b=>b.classList.toggle('active',b.dataset.category===window._nfFoodCategory));const i=document.getElementById('foodSearch');if(i)i.value='';window._selectedFoodName='';const sel=document.getElementById('selectedFood');if(sel)sel.classList.add('hidden');filterFoodPicker()}
function clearFoodSearch(){window._nfFoodCategory='';const i=document.getElementById('foodSearch');if(i)i.value='';window._selectedFoodName='';document.querySelectorAll('.nf-food-category').forEach(b=>b.classList.remove('active'));const sel=document.getElementById('selectedFood');if(sel)sel.classList.add('hidden');filterFoodPicker()}
function pickFoodQuick(encoded){const name=decodeURIComponent(encoded||'');if(!allFoods()[name])return;selectFood(name)}
function selectFood(value){const name=decodeURIComponent(value||'');const f=allFoods()[name];if(!f)return;window._selectedFoodName=name;window._nfMealUnitInitialized=false;renderMealComposer()}
function preferredMealUnit(f,current=''){const opts=f?.unitMode==='portion'?[{value:'portion',label:f.unitLabel||'porción'}]:(Array.isArray(f?.unitOptions)&&f.unitOptions.length?f.unitOptions:[{value:'g',label:'g',gramsPerUnit:1}]);if(current&&opts.some(o=>o.value===current))return current;return (opts.find(o=>o.value!=='g'&&o.value!=='ml')||opts[0]).value}
function updateMealUnitUI(preserve=true){const f=allFoods()[window._selectedFoodName],u=document.getElementById('qtyUnit'),q=document.getElementById('qty');if(!f||!u||!q)return;const opts=f.unitMode==='portion'?[{value:'portion',label:f.unitLabel||'porción'}]:(Array.isArray(f.unitOptions)&&f.unitOptions.length?f.unitOptions:[{value:'g',label:'g',gramsPerUnit:1}]);const old=preserve?u.value:'';u.innerHTML=opts.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('');u.value=preferredMealUnit(f,old);q.step=u.value==='g'||u.value==='ml'?'1':'0.25';q.min='0.25';if(!q.value)q.value=f.unitMode==='portion'?'1':''}
function setMealDraftRole(role){const d=window._nfMealDraft;if(!d)return;d.activeRole=normalizeMealRole(role);window._selectedFoodName='';window._nfFoodCategory='';renderMealComposer()}
function beginMealRoleAdd(role){setMealDraftRole(role);const focusSelector=()=>{const nav=document.getElementById('foodCategoryNav'),input=document.getElementById('foodSearch');if(nav&&typeof nav.scrollIntoView==='function')nav.scrollIntoView({block:'start',behavior:'auto'});if(input&&typeof input.focus==='function')input.focus({preventScroll:true})};if(typeof requestAnimationFrame==='function')requestAnimationFrame(focusSelector);else setTimeout(focusSelector,0)}
function addMealDraftItemUI(){const draft=window._nfMealDraft,name=window._selectedFoodName,unit=document.getElementById('qtyUnit')?.value||'g',amount=Number(String(document.getElementById('qty')?.value||'').replace(',','.'));if(!draft||!name)return alert('Seleccioná un alimento.');if(!Number.isFinite(amount)||amount<=0)return alert('Ingresá una cantidad válida.');const p=getActiveProfile(),e=calcEntryFromFood(name,amount,{pid:p.id,date:window.journalDate||localDate(),type:draft.type,inputUnit:unit,estimate:false,confidence:1});if(!e)return alert('Cantidad, alimento o unidad inválidos.');addMealDraftItem(draft,e,draft.activeRole);window._selectedFoodName='';window._nfFoodCategory='';renderMealComposer()}
function removeMealDraftItemUI(i){removeMealDraftItem(window._nfMealDraft,Number(i));renderMealComposer()}
function editMealDraftItemUI(i){const d=window._nfMealDraft,item=d?.items?.[Number(i)];if(!item)return;const names=_nfFoodList('',item.categoryId||'');const fs=allFoods();const available=names.length?names:Object.keys(fs).filter(n=>typeof searchFoods==='function'&&searchFoods('', '').includes(n)).slice(0,80);openModal({title:'Editar componente',body:`<label>Componente</label><select id="mdfood">${available.map(n=>`<option value="${esc(n)}" ${n===item.food?'selected':''}>${esc(n)}</option>`).join('')}</select><div class="unitrow"><div><label>Cantidad</label><input id="mdqty" type="number" min="0.25" step="1" value="${esc(item.amount)}"></div><div><label>Unidad</label><select id="mdunit"></select></div></div><label>Componente</label><select id="mdrole">${MEAL_ROLES.map(r=>`<option value="${r}" ${normalizeMealRole(item.mealRole)===r?'selected':''}>${MEAL_ROLE_LABELS[r]}</option>`).join('')}</select><button type="button" onclick="saveMealDraftItemEdit(${Number(i)})">Guardar cambios</button>`});window._selectedFoodName=item.food;const f=fs[item.food];const opts=f?.unitMode==='portion'?[{value:'portion',label:f.unitLabel||'porción'}]:(Array.isArray(f?.unitOptions)&&f.unitOptions.length?f.unitOptions:[{value:'g',label:'g',gramsPerUnit:1}]);const u=document.getElementById('mdunit');if(u){u.innerHTML=opts.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('');u.value=opts.some(o=>o.value===item.inputUnit)?item.inputUnit:preferredMealUnit(f,'')} }
function saveMealDraftItemEdit(i){const d=window._nfMealDraft;if(!d)return;const name=document.getElementById('mdfood')?.value,qty=Number(String(document.getElementById('mdqty')?.value||'').replace(',','.')),unit=document.getElementById('mdunit')?.value||'g',role=normalizeMealRole(document.getElementById('mdrole')?.value);const p=getActiveProfile();const e=calcEntryFromFood(name,qty,{pid:p.id,date:window.journalDate||localDate(),type:d.type,inputUnit:unit,estimate:false,confidence:1,id:d.items[i]?.id});if(!e)return alert('Revisá alimento, cantidad y unidad.');updateMealDraftItem(d,i,{...e,mealRole:role});closeModal();window._selectedFoodName='';renderMealComposer()}
function saveMealDraft(){const draft=window._nfMealDraft;if(!draft||!draft.items.length)return alert('Agregá al menos un alimento.');const start=db.entries.length,items=draft.items.map(e=>({...e,mealRole:normalizeMealRole(e.mealRole),id:`e_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}));db.entries.push(...items);if(!save()){db.entries.splice(start,items.length);return}window._nfMealDraft=null;window._selectedFoodName='';closeModal();render()}
function saveMeal(){addMealDraftItemUI()}

function updateEditUnitUI(preserve=false,initial=null,initialUnit=null){const s=document.getElementById('efood'),l=document.getElementById('eqtyLabel'),q=document.getElementById('eqty'),u=document.getElementById('eqtyUnit');if(!s||!l||!q||!u)return;const f=allFoods()[s.value];if(!f){u.innerHTML='';return}const opts=f.unitMode==='portion'?[{value:'portion',label:f.unitLabel||'porción'}]:(Array.isArray(f.unitOptions)&&f.unitOptions.length?f.unitOptions:[{value:'g',label:'g',gramsPerUnit:1}]);u.innerHTML=opts.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('');const wanted=initialUnit||u.value;u.value=opts.some(o=>o.value===wanted)?wanted:(opts.some(o=>o.value==='g')?'g':opts[0].value);l.textContent='Cantidad';q.step=u.value==='g'||u.value==='ml'?'1':'0.25';q.min='0.25';if(!preserve)q.value=f.unitMode==='portion'?'1':'1';else if(initial!=null)q.value=initial}
function editEntry(i){const p=getActiveProfile(),date=window.journalDate||localDate(),arr=entriesFor(date,p.id),x=arr[i];if(!x)return;const visibleNames=typeof searchFoods==='function'?searchFoods(''):Object.keys(allFoods());const names=visibleNames.includes(x.food)?visibleNames:([x.food,...visibleNames]);const amount=Number.isFinite(Number(x.amount))?x.amount:(Number.isFinite(Number(x.qty))?x.qty:(x.inputUnit==='g'&&Number.isFinite(Number(x.grams))?x.grams:'')),unit=x.inputUnit||'g';openModal({title:'Editar comida',body:`<label>Comida</label><select id="efood" onchange="updateEditUnitUI()">${names.map(n=>`<option value="${esc(n)}" ${n===x.food?'selected':''}>${esc(n)}</option>`).join('')}</select><div class="unitrow"><div><label id="eqtyLabel">Cantidad</label><input id="eqty" type="number" value="${amount}" step="1" min="0.25"></div><div><label>Unidad</label><select id="eqtyUnit"></select></div></div><label>Componente</label><select id="erole"><option value="">Sin clasificar</option>${MEAL_ROLES.map(r=>`<option value="${r}" ${x.mealRole===r?'selected':''}>${MEAL_ROLE_LABELS[r]}</option>`).join('')}</select><label>Momento</label><select id="etype">${_nfMealTypes().map(n=>`<option ${n===x.type?'selected':''}>${n}</option>`).join('')}</select><button onclick="saveEditEntry(${i})">Guardar cambios</button>`});updateEditUnitUI(true,amount,unit)}
function saveEditEntry(i){const p=getActiveProfile(),date=window.journalDate||localDate(),arr=entriesFor(date,p.id),old=arr[i],idx=db.entries.indexOf(old);if(idx<0)return;const name=document.getElementById('efood')?.value,qty=Number(String(document.getElementById('eqty')?.value||'').replace(',','.')),unit=document.getElementById('eqtyUnit')?.value||'g';if(!name||!Number.isFinite(qty)||qty<=0)return alert('Revisá alimento y cantidad.');const entry=calcEntryFromFood(name,qty,{pid:p.id,date,type:document.getElementById('etype').value,id:db.entries[idx].id,inputUnit:unit,mealRole:(document.getElementById('erole')?.value||old.mealRole||undefined)});if(!entry)return alert('No pude recalcular ese alimento o unidad.');const prev=db.entries[idx];db.entries[idx]=entry;if(!save()){db.entries[idx]=prev;return}closeModal();render()}
function deleteEntry(i){const p=getActiveProfile(),date=window.journalDate||localDate(),arr=entriesFor(date,p.id),old=arr[i],idx=db.entries.indexOf(old);if(idx<0)return;if(!confirm(`¿Eliminar ${old.food} de ${date}?`))return;const removed=db.entries.splice(idx,1)[0];if(!save()){db.entries.splice(idx,0,removed);return}render()}
