function objectiveLabel(id){return OBJECTIVES[id]?.label||id}
function getObjectives(p){let ids=Array.isArray(p.objectives)&&p.objectives.length?p.objectives:[p.goalType==='Bajar peso'?'lose_fat':'food_quality'];return ids.filter(id=>OBJECTIVES[id])}
function compatibleObjectives(ids){const out=[];for(const a of ids){for(const b of ids){if(a===b)continue;if(!OBJECTIVE_COMPAT[a]?.has(b))out.push([a,b]);}}return out.filter((x,i)=>out.findIndex(y=>y[0]===x[1]&&y[1]===x[0])<i)}
function objectiveProfile(p){const ids=getObjectives(p),conflicts=compatibleObjectives(ids);const has=id=>ids.includes(id);let mode='general';if(has('recomp')||(has('lose_fat')&&has('gain_muscle')))mode='recomp';else if(has('gain_muscle'))mode='muscle';else if(has('lose_fat'))mode='fat_loss';else if(has('maintain'))mode='maintenance';return {ids,conflicts,mode,labels:ids.map(objectiveLabel)}}
function objectiveSummary(p){const op=objectiveProfile(p);if(op.conflicts.length)return 'Hay objetivos que compiten entre sí; revisá prioridades.';if(op.mode==='recomp')return 'Modo recomposición: perder grasa mientras se preserva/puede ganar masa muscular, con fuerza y proteína adecuadas.';if(op.mode==='muscle')return 'Modo masa muscular: prioriza entrenamiento de fuerza, proteína suficiente y energía adecuada.';if(op.mode==='fat_loss')return 'Modo pérdida de grasa: prioriza déficit moderado, proteína suficiente, fibra y adherencia.';if(op.mode==='maintenance')return 'Modo mantenimiento: prioriza estabilidad de peso, calidad dietaria y actividad.';return 'Modo salud y calidad: prioriza patrón alimentario, fibra, vegetales y moderación de sodio, azúcares y grasas saturadas.'}

const foodMeta={
 'Pechuga de pollo':'whole','Pollo muslo sin piel':'whole','Patamuslo sin piel':'whole','Carne vacuna magra':'whole','Bife de carne magra':'whole','Vacío magro':'whole','Bondiola de cerdo':'whole','Cerdo magro':'whole','Atún al natural':'whole','Sardinas en aceite':'whole','Merluza':'whole','Salmón':'whole','Huevo hervido':'whole','Huevo revuelto':'whole','Brócoli':'plant','Coliflor':'plant','Lechuga':'plant','Tomate':'plant','Rúcula':'plant','Cebolla':'plant','Morrón':'plant','Zanahoria':'plant','Pepino':'plant','Verdeo':'plant','Champiñones':'plant','Palta':'plant','Banana':'plant','Manzana':'plant','Pera':'plant','Naranja':'plant','Kiwi':'plant','Frutilla':'plant','Arándanos':'plant','Limón':'plant','Lentejas cocidas':'plant','Garbanzos cocidos':'plant','Avena en hojuelas':'plant','Pan blanco':'ultra','Factura':'ultra','Alfajor':'ultra','Pizza muzzarella':'ultra','Mayonesa':'ultra','Milanesa de pollo':'processed','Milanesa de carne':'processed'
};
function foodWithMeta(name,v){const o={...v};o.state=o.state||(/\bcrudo\b/i.test(name)?'crudo':/\b(hervido|cocido|plancha|horno|asado|salteado|revuelto)\b/i.test(name)?(name.match(/\b(hervido|cocido|plancha|horno|asado|salteado|revuelto)\b/i)||[])[1]:'sin especificar');o.basis=o.basis||(o.unitMode==='portion'?`por ${o.unitLabel||'porción'}`:'por 100 g');o.source=o.source||'Base local provisional';o.sourceStatus=o.sourceStatus||'Pendiente de validación alimento por alimento';o.unitOptions=Array.isArray(o.unitOptions)?o.unitOptions:[{value:'g',label:'g',gramsPerUnit:1}];return o}
