function newRecipe(){openModal({title:'🥘 Nueva receta',body:`<p class="muted small">Empezá con 0 ingredientes. Agregá cada alimento, cantidad y unidad. Podés usar “unidad” cuando la equivalencia esté documentada.</p><label>Nombre</label><input id="rname" placeholder="Ej. Tortilla de huevo y verduras"><label>Porciones que rinde</label><input id="rport" type="number" value="2" min="0.25" step="0.25"><div id="rrows"></div><button class="secondary" onclick="addRecipeRow()">＋ Agregar ingrediente</button><button onclick="saveRecipe()">Guardar receta</button>`})}
function recipeUnitOptions(f){if(!f)return[{value:'g',label:'g'}];if(f.unitMode==='portion')return[{value:'portion',label:f.unitLabel||'porción'}];return (Array.isArray(f.unitOptions)?f.unitOptions:[{value:'g',label:'g'}]).map(o=>({value:o.value,label:o.label}))}
function updateRecipeRowUnit(row){const s=row.querySelector('.ri'),u=row.querySelector('.ru'),q=row.querySelector('.rq'),h=row.querySelector('.rhelp');if(!s||!u||!q)return;const f=allFoods()[s.value],opts=recipeUnitOptions(f),old=u.value;u.innerHTML=opts.map(o=>'<option value="'+esc(o.value)+'">'+esc(o.label)+'</option>').join('');u.value=opts.some(o=>o.value===old)?old:opts[0].value;q.step=u.value==='g'?'1':'0.5';q.min=u.value==='g'?'0.5':'0.25';if(h)h.textContent=f?'Unidad disponible: '+opts.map(o=>o.label).join(' · '):'Escribí un alimento válido.'}
function addRecipeRow(item=null){const box=document.getElementById('rrows');if(!box)return;let dl=document.getElementById('recipeFoods');if(!dl){dl=document.createElement('datalist');dl.id='recipeFoods';dl.innerHTML=Object.keys(allFoods()).sort((a,b)=>a.localeCompare(b,'es')).map(x=>'<option value="'+esc(x)+'">').join('');box.parentNode.appendChild(dl)}const row=document.createElement('div');row.className='card recipe-row';row.innerHTML='<label>Ingrediente</label><input class="ri" list="recipeFoods" placeholder="Ej. Huevo crudo, cebolla cruda…"><div class="unitrow"><input class="rq" type="number" min="0.5" step="1" placeholder="Ej: 100"><select class="ru"></select><button class="danger small" type="button" onclick="this.closest(\'.recipe-row\').remove()">Eliminar</button></div><small class="muted rhelp"></small>';box.appendChild(row);const sel=row.querySelector('.ri');if(item?.food&&allFoods()[item.food])sel.value=item.food;sel.oninput=()=>updateRecipeRowUnit(row);sel.onchange=()=>updateRecipeRowUnit(row);updateRecipeRowUnit(row);if(item){row.querySelector('.rq').value=item.q;updateRecipeRowUnit(row);row.querySelector('.ru').value=item.unitInput||item.unitMode||'g'}}
function calcRecipeIngredients(ings){const sum={kcal:0,p:0,c:0,f:0,fib:0,sugar:0,sat:0,sodium:0,veg:0,fruit:0,plantCount:0,wholeFoodCount:0,ultraCount:0};const MICRO=NUTRIENT_FIELDS.slice(8);for(const k of MICRO)sum[k]=0;const complete=Object.fromEntries(MICRO.map(k=>[k,true]));const plants=new Set();for(const i of ings){const e=calcEntryFromFood(i.food,i.q,{inputUnit:i.unitInput});if(!e)return null;Object.keys(sum).forEach(k=>{if(MICRO.includes(k)&&e[k]===undefined)complete[k]=false;else if(Number.isFinite(Number(e[k])))sum[k]+=Number(e[k])});const ff=allFoods()[i.food];if(Array.isArray(ff.plantKeys))ff.plantKeys.forEach(k=>plants.add(k));if(ff.plantKey)plants.add(ff.plantKey);if(ff.processing==='ultra')sum.ultraCount+=1;if(ff.processing==='whole')sum.wholeFoodCount+=1}sum.plantCount=plants.size;MICRO.forEach(k=>{if(!complete[k])sum[k]=undefined});return {...sum,plantKeys:[...plants],unknownNutrients:MICRO.filter(k=>!complete[k])}}
function saveRecipe(){const name=document.getElementById('rname').value.trim(),port=Number(String(document.getElementById('rport').value||'').replace(',','.'));if(!name||!Number.isFinite(port)||port<=0||port>100)return alert('Nombre y número de porciones válidos.');const rows=[...document.querySelectorAll('#rrows .recipe-row')],ing=rows.map(r=>({food:r.querySelector('.ri').value,q:Number(String(r.querySelector('.rq').value||'').replace(',','.')),unitInput:r.querySelector('.ru').value}));if(!ing.length||ing.some(i=>!i.food))return alert('Agregá al menos un ingrediente válido.');if(ing.some(i=>!Number.isFinite(i.q)||i.q<=0||i.q>10000))return alert('Revisá las cantidades.');const sum=calcRecipeIngredients(ing);if(!sum)return alert('Hay un ingrediente con unidad o cantidad no utilizable.');const rec={id:Date.now().toString(),name,portions:port,ingredients:ing,...sum};db.recipes.push(rec);if(!save()){db.recipes.pop();return}closeModal();render()}
function editRecipe(id){const r=db.recipes.find(x=>x.id===id);if(!r)return;openModal({title:`✏️ Editar receta: ${esc(r.name)}`,body:`<label>Nombre</label><input id="rename" value="${esc(r.name)}"><label>Porciones que rinde</label><input id="report" type="number" min="0.25" max="100" step="0.25" value="${r.portions}"><div id="rrows"></div><div class="actions"><button class="secondary" onclick="addRecipeRow()">＋ Ingrediente</button><button onclick="saveEditRecipeFull('${esc(r.id)}')">Guardar cambios</button></div>`});(r.ingredients||[]).forEach(it=>addRecipeRow(it))}
function saveEditRecipeFull(id){const r=db.recipes.find(x=>x.id===id);if(!r)return;const n=document.getElementById('rename').value.trim(),p=Number(String(document.getElementById('report').value||'').replace(',','.'));const rows=[...document.querySelectorAll('#rrows .recipe-row')],ing=rows.map(r=>({food:r.querySelector('.ri').value,q:Number(String(r.querySelector('.rq').value||'').replace(',','.')),unitInput:r.querySelector('.ru').value}));if(!n||!Number.isFinite(p)||p<=0||p>100||!ing.length||ing.some(i=>!i.food||!Number.isFinite(i.q)||i.q<=0))return alert('Revisá nombre, porciones e ingredientes.');const sum=calcRecipeIngredients(ing);if(!sum)return alert('Hay un ingrediente con unidad o cantidad no utilizable.');const old=JSON.parse(JSON.stringify(r));Object.assign(r,{name:n,portions:p,ingredients:ing,...sum});if(!save()){Object.assign(r,old);return}closeModal();render()}



function saveRecipeMeal(id){let r=db.recipes.find(x=>x.id===id);if(!r)return;let q=Number(String(document.getElementById('rqty').value||'').replace(',','.'));if(!Number.isFinite(q)||q<=0||q>r.portions*10)return alert('Ingresá una cantidad válida de porciones.');let fac=q/r.portions;let keys=['kcal','p','c','f','fib','sugar','sat','sodium','veg','fruit','plantCount','wholeFoodCount','ultraCount','calcium','iron','magnesium','potassium','vitC','vitD','vitE','b12','folate','omega3','omega6','zinc','phosphorus','iodine','cholesterol'];let entry={pid:getActiveProfile().id,date:window.journalDate||localDate(),food:r.name,amount:q,qty:q,unit:'porciones',unitMode:'portion',grams:null,type:document.getElementById('rtype').value,estimate:false,confidence:1,source:'Receta propia',sourceStatus:'calculada con ingredientes registrados'};keys.forEach(k=>{if(r[k]!==undefined)entry[k]=Number(r[k])*fac});entry.unknownNutrients=Array.isArray(r.unknownNutrients)?r.unknownNutrients.slice():[];db.entries.push(entry);const ok=save();if(!ok){db.entries.pop();return}closeModal();render()}
function useRecipe(id){const r=db.recipes.find(x=>x.id===id);if(!r)return;openModal({title:`Usar: ${esc(r.name)}`,body:`<p class="muted">La receta tiene ${r.portions} porciones.</p><label>Porciones consumidas</label><input id="rqty" type="number" min="0.25" max="${Math.max(.25,r.portions*10)}" value="1" step="0.25"><label>Momento</label><select id="rtype"><option>Almuerzo</option><option>Cena</option><option>Desayuno</option><option>Merienda</option><option>Snack</option></select><button onclick="saveRecipeMeal('${esc(r.id)}')">Registrar</button>`})}

function saveEditRecipeLegacy(id){const r=db.recipes.find(x=>x.id===id);if(!r)return;const n=document.getElementById('rename').value.trim(),p=Number(String(document.getElementById('report').value||'').replace(',','.'));if(!n||!Number.isFinite(p)||p<=0||p>100)return alert('Nombre y porciones válidos.');const old={name:r.name,portions:r.portions};r.name=n;r.portions=p;if(!save()){Object.assign(r,old);return}closeModal();render()}
function deleteRecipe(id){const r=db.recipes.find(x=>x.id===id);if(!r)return;if(!confirm(`¿Eliminar definitivamente la receta «${r.name}»?`))return;const idx=db.recipes.indexOf(r);const removed=db.recipes.splice(idx,1)[0];if(!save()){db.recipes.splice(idx,0,removed);return}render()}
