let db=loadDB();

function localDate(d=new Date()){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function safeParseJSON(v){try{return v?JSON.parse(v):null}catch(_){return null}}
function loadDB(){
 const cur=safeParseJSON(localStorage.getItem(KEY));
 if(cur) return normalize(cur);
 return normalize({version:VERSION,profiles:[],active:null,entries:[],weights:[],waterByDate:{},stepsByDate:{},sleepByDate:{},recipes:[],customFoods:[],favoriteFoods:[],photoLogs:[],glucoseLogs:[],healthLogs:[],targetHistory:[]});
}

function ensureFamilyModel(x){
  x.familyVersion=2;
  x.familyName=x.familyName||'Mi familia';
  x.profiles=Array.isArray(x.profiles)?x.profiles:[];
  x.profiles.forEach((p,i)=>{
    p.id=String(p.id||('person_'+Date.now()+'_'+i));
    p.name=String(p.name||`Persona ${i+1}`);
    p.role=p.role||'familiar';
    p.permissions=p.permissions||{canEdit:true,canDelete:true};
    p.objectives=getObjectives(p);
  });
  if(!x.active&&x.profiles[0])x.active=x.profiles[0].id;
  return x;
}
function familyMembers(){return Array.isArray(db.profiles)?db.profiles:[]}
function switchPerson(id){if(!familyMembers().some(p=>p.id===id))return;const old=db.active;db.active=id;if(!save()){db.active=old;return}render()}
function addFamilyMember(){newProfile()}

function normalize(x){
 x=ensureFamilyModel(x);
 x.profiles=Array.isArray(x.profiles)?x.profiles:[];
 const profileMap=new Map(),used=new Set();
 x.profiles.forEach((p,i)=>{const old=String(p.id||'');let id=old.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,32);if(!id)id=`p_${Math.random().toString(36).slice(2,9)}`;while(used.has(id)){id=`p_${Math.random().toString(36).slice(2,9)}`;}used.add(id);profileMap.set(old,id);p.id=id;});
 const remapPid=o=>{if(o&&o.pid!=null)o.pid=profileMap.get(String(o.pid))||String(o.pid);return o};
 x.entries=Array.isArray(x.entries)?x.entries.map(remapPid):[];x.weights=Array.isArray(x.weights)?x.weights.map(remapPid):[];
 const validIds=new Set(x.profiles.map(p=>p.id)), validDates=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v));
 x.entries=x.entries.map((e,i)=>{const out={...e};out.pid=String(out.pid||'');out.date=String(out.date||'');out.food=String(out.food||'').slice(0,160);out.type=['Desayuno','Almuerzo','Merienda','Cena','Snack'].includes(out.type)?out.type:'Snack';let fmeta=foodUnitMeta(out.food,out);let rawAmount=Number(out.amount ?? out.qty ?? out.grams);let rawUnit=String(out.inputUnit||out.unit||'g');if(/^huevo crudo$/i.test(out.food)&&(!out.unitOptions||!Array.isArray(out.unitOptions))&&rawUnit==='g'&&Number.isFinite(rawAmount)&&rawAmount>0&&rawAmount<=3){rawUnit='unit';rawAmount=rawAmount;out.inputUnit='unit';out.unitOptions=[{value:'g',label:'g',gramsPerUnit:1},{value:'unit',label:'1 huevo (sin cáscara)',gramsPerUnit:50}];out.unitMode='per100g';out.unit='1 huevo (sin cáscara)';out.grams=rawAmount*50;out.qty=rawAmount;out.amount=rawAmount;const ef=foods['Huevo crudo'];if(ef){const fac=out.grams/100;out.kcal=(ef.kcal||0)*fac;out.p=(ef.p||0)*fac;out.c=(ef.c||0)*fac;out.f=(ef.f||0)*fac;out.fib=(ef.fib||0)*fac;out.sugar=(ef.sugar||0)*fac;out.sat=(ef.sat||0)*fac;out.sodium=(ef.sodium||0)*fac;}}else{if(!Array.isArray(out.unitOptions)||!out.unitOptions.length)out.unitOptions=fmeta.unitOptions||[{value:'g',label:'g',gramsPerUnit:1}];out.unitMode=fmeta.unitMode;out.inputUnit=rawUnit;const selected=out.unitOptions.find(o=>o.value===rawUnit)||out.unitOptions.find(o=>o.value===out.unit)||out.unitOptions[0];out.inputUnit=selected.value;out.unit=selected.label||'g';out.amount=Number.isFinite(rawAmount)&&rawAmount>0&&rawAmount<=10000?rawAmount:null;out.qty=out.amount;out.grams=out.unitMode==='per100g'?(Number(selected.gramsPerUnit)>0?out.amount*Number(selected.gramsPerUnit):out.amount):null;}for(const k of ['kcal','p','c','f','fib','sugar','sat','sodium','veg','fruit','plantCount','wholeFoodCount','ultraCount']){const v=Number(out[k]);out[k]=Number.isFinite(v)&&v>=0?v:0}for(const k of NUTRIENT_FIELDS.slice(8)){if(out[k]!==undefined){const v=Number(out[k]);if(Number.isFinite(v)&&v>=0)out[k]=v;else delete out[k]}}return out}).filter(e=>validIds.has(e.pid)&&validDates(e.date)&&e.food&&e.amount);
 x.weights=x.weights.map((w,i)=>({...w,pid:String(w.pid||''),date:String(w.date||''),kg:Number(w.kg),source:String(w.source||'manual').slice(0,60)})).filter(w=>validIds.has(w.pid)&&validDates(w.date)&&Number.isFinite(w.kg)&&w.kg>=30&&w.kg<=300);

 x.photoLogs=Array.isArray(x.photoLogs)?x.photoLogs.map(remapPid):[];x.glucoseLogs=Array.isArray(x.glucoseLogs)?x.glucoseLogs.map(remapPid):[];x.healthLogs=Array.isArray(x.healthLogs)?x.healthLogs.map(remapPid):[];x.targetHistory=Array.isArray(x.targetHistory)?x.targetHistory.map(remapPid):[];
 for(const obj of ['waterByDate','stepsByDate','sleepByDate']){const out={};for(const [k,v] of Object.entries(x[obj]||{})){const [pid,...rest]=String(k).split('|'),mapped=profileMap.get(pid)||pid,date=rest.join('|');if(validIds.has(mapped)&&validDates(date)){const n=Number(v);if(Number.isFinite(n)&&n>=0)out[`${mapped}|${date}`]=Math.min(obj==='waterByDate'?10000:50000,n)}}x[obj]=out}
 if(x.healthSync){const hs={};for(const [pid,v] of Object.entries(x.healthSync))hs[profileMap.get(pid)||pid]=v;x.healthSync=hs}
 x.active=profileMap.get(String(x.active||''))||x.profiles[0]?.id||null;
 x.entries=Array.isArray(x.entries)?x.entries:[];x.weights=Array.isArray(x.weights)?x.weights:[];x.favoriteFoods=Array.isArray(x.favoriteFoods)?x.favoriteFoods.map(remapPid).map(o=>({...o,pid:String(o.pid||''),food:String(o.food||'').slice(0,160)})).filter(o=>validIds.has(o.pid)&&o.food):[];x.customFoods=Array.isArray(x.customFoods)?x.customFoods:[];x.customFoods=x.customFoods.map(f=>{const o={...f,name:String(f.name||'').trim().slice(0,120)};for(const k of ['kcal','p','c','f','fib','sugar','sat','sodium','veg','fruit','calcium','iron','magnesium','potassium','vitC','vitD','vitE','b12','folate','omega3','omega6','zinc','phosphorus','iodine','cholesterol']){if(o[k]!==undefined){const v=Number(o[k]);if(Number.isFinite(v)&&v>=0)o[k]=v;else delete o[k]}}o.unitMode=o.unitMode==='portion'?'portion':'per100g';o.unitLabel=String(o.unitLabel||(o.unitMode==='portion'?'porción':'g')).slice(0,40);o.basis=String(o.basis||(o.unitMode==='portion'?`por ${o.unitLabel}`:'por 100 g de porción comestible')).slice(0,120);o.source=String(o.source||'Alimento personalizado').slice(0,120);o.sourceStatus=String(o.sourceStatus||'dato aportado/verificado por el usuario; no es composición científica primaria').slice(0,180);o.barcode=o.barcode?String(o.barcode).replace(/[^0-9]/g,'').slice(0,32):'';return o}).filter(f=>f.name);x.recipes=Array.isArray(x.recipes)?x.recipes:[];x.photoLogs=Array.isArray(x.photoLogs)?x.photoLogs:[];x.glucoseLogs=Array.isArray(x.glucoseLogs)?x.glucoseLogs:[];x.healthLogs=Array.isArray(x.healthLogs)?x.healthLogs:[];
 x.waterByDate=(x.waterByDate&&typeof x.waterByDate==='object'&&!Array.isArray(x.waterByDate))?x.waterByDate:{};x.stepsByDate=(x.stepsByDate&&typeof x.stepsByDate==='object'&&!Array.isArray(x.stepsByDate))?x.stepsByDate:{};x.sleepByDate=(x.sleepByDate&&typeof x.sleepByDate==='object'&&!Array.isArray(x.sleepByDate))?x.sleepByDate:{};x.ai=x.ai&&typeof x.ai==='object'?x.ai:{enabled:false,mode:'proxy',model:'',apiKey:'',endpoint:''};x.ai.apiKey='';x.ai.mode='proxy';x.glucoseLogs=Array.isArray(x.glucoseLogs)?x.glucoseLogs:[];x.healthLogs=Array.isArray(x.healthLogs)?x.healthLogs:[];
 if(x.water && !Object.keys(x.waterByDate).length){const pid=x.active||x.profiles?.[0]?.id;if(pid)x.waterByDate[`${pid}|${localDate()}`]=x.water;}
 if(x.steps && !Object.keys(x.stepsByDate).length){const pid=x.active||x.profiles?.[0]?.id;if(pid)x.stepsByDate[`${pid}|${localDate()}`]=x.steps;}
 x.profiles.forEach(p=>{p.name=String(p.name||'Usuario').slice(0,80);p.objectives=getObjectives(p);const _validGoalTypes=['lose_fat','maintain','gain_muscle','recomp','food_quality','glycemic','cardiovascular','longevity'];p.goalType=_validGoalTypes.includes(p.goalType)?p.goalType:(_validGoalTypes.includes(p.objectives[0])?p.objectives[0]:'maintain');p.pattern=['balanced','lowcarb','verylowcarb','ketohighprotein','highprotein','mediterranean','medlowcarb','dash','vegetarian','vegan','longevity','calorie'].includes(p.pattern)?p.pattern:'balanced';p.age=Number.isFinite(Number(p.age))?Number(p.age):null;p.height=Number.isFinite(Number(p.height))?Number(p.height):null;p.cal=Number.isFinite(Number(p.cal))&&Number(p.cal)>0?Number(p.cal):1900;p.pr=Number.isFinite(Number(p.pr))&&Number(p.pr)>0?Number(p.pr):120;p.water=Number.isFinite(Number(p.water))&&Number(p.water)>0?Number(p.water):null;p.steps=0;p.goal=Number.isFinite(Number(p.goal))&&Number(p.goal)>=30&&Number(p.goal)<=300?Number(p.goal):null;p.targetMode=['auto','manual'].includes(p.targetMode)?p.targetMode:'auto';p.targetProteinMode=['normal','high'].includes(p.targetProteinMode)?p.targetProteinMode:'normal';p.calSource=p.calSource||'manual';p.prSource=p.prSource||'manual';p.targetUpdatedAt=p.targetUpdatedAt||null;p.allergies=(Array.isArray(p.allergies)?p.allergies:[]).map(x=>String(x).trim()).filter(Boolean).slice(0,30);p.dislikes=(Array.isArray(p.dislikes)?p.dislikes:[]).map(x=>String(x).trim()).filter(Boolean).slice(0,30);});
 x.recipes=x.recipes.map((r,i)=>{const rid=String(r.id||`r_${i}_${Math.random().toString(36).slice(2,8)}`).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,48)||`r_${i}_${Math.random().toString(36).slice(2,8)}`;const ingredients=Array.isArray(r.ingredients)?r.ingredients.map(it=>({food:String(it.food||''),q:Number.isFinite(Number(it.q))&&Number(it.q)>0&&Number(it.q)<=10000?Number(it.q):null,unitMode:it.unitMode==='portion'?'portion':'per100g',unitInput:String(it.unitInput||it.unit||'g'),unit:String(it.unit||it.unitInput||'g')})).filter(it=>it.food&&it.q):[];const out={...r,id:rid,name:String(r.name||'Receta').slice(0,100),portions:Number.isFinite(Number(r.portions))&&Number(r.portions)>0&&Number(r.portions)<=100?Number(r.portions):1,ingredients,unknownNutrients:Array.isArray(r.unknownNutrients)?r.unknownNutrients.filter(k=>NUTRIENT_FIELDS.slice(8).includes(k)):[],plantKeys:Array.isArray(r.plantKeys)?r.plantKeys.map(String).filter(Boolean).slice(0,100):[]};for(const k of ['kcal','p','c','f','fib','sugar','sat','sodium','veg','fruit','plantCount','wholeFoodCount','ultraCount',...NUTRIENT_FIELDS.slice(8)]){const v=Number(out[k]);out[k]=Number.isFinite(v)&&v>=0?v:0}return out;});
 return x;
}
function save(){db.version=VERSION;try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch(e){const quota=e&&((e.name==='QuotaExceededError')||e.code===22||e.code===1014);alert(quota?'El almacenamiento del teléfono está lleno. Exportá una copia de seguridad, liberá espacio y volvé a intentar.':'No se pudieron guardar los datos en este teléfono. Revisá el espacio disponible y los permisos del navegador.');window.NF_RUNTIME.errors.push({type:quota?'storage-quota':'storage',message:e.message||String(e)});return false}}
function getActiveProfile(){return db.profiles.find(x=>x.id===db.active)||db.profiles[0]}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function foodUnitMeta(name,v){const n=String(name||'');if(v&&Array.isArray(v.unitOptions)&&v.unitOptions.length){return {unitMode:v.unitMode==='portion'?'portion':'per100g',unitLabel:v.unitLabel||'g',unitOptions:v.unitOptions}}if(v&&v.unitMode)return v.unitMode==='portion'?{unitMode:'portion',unitLabel:v.unitLabel||'porción'}:{unitMode:'per100g',unitLabel:'g',unitOptions:[{value:'g',label:'g',gramsPerUnit:1}]};if(/\(1 porción\)/i.test(n)||/^2 empanadas /i.test(n)||/^Omelette de 2 huevos$/i.test(n)||/^Aceite \(1 cucharadita\)$/i.test(n))return {unitMode:'portion',unitLabel:/Aceite/i.test(n)?'cucharadita':/^2 empanadas/i.test(n)?'2 empanadas':'porción'};return {unitMode:'per100g',unitLabel:'g',unitOptions:[{value:'g',label:'g',gramsPerUnit:1}]}}
function allFoods(){
 let raw={...foods,...Object.fromEntries(db.customFoods.map(x=>[x.name,x]))};
 return Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,foodWithMeta(k,{processing:'unknown',plant:false,group:'general',...(microDB[k]||{}),...v,...foodUnitMeta(k,v)})]));
}
const PLAN_DEFS={
 balanced:{label:'⚖️ Equilibrada',carbMode:'percent',carbPct:[45,65],protein:[1.2,1.6],note:'Distribución convencional de macronutrientes; los hidratos se calculan como 45–65% de la energía.'},
 lowcarb:{label:'🥩 Low Carb 50–70 g',carb:[50,70],protein:[1.2,1.6],note:'Plan de bajo contenido en hidratos configurado para el seguimiento actual de la familia.'},
 verylowcarb:{label:'🥑 Keto 20–50 g',carb:[20,50],protein:[1.2,1.6],note:'Patrón muy bajo en hidratos; este rango es una configuración del plan, no una garantía de cetosis.'},
 ketohighprotein:{label:'🥑💪 Keto alta en proteína 20–40 g',carb:[20,40],protein:[1.6,2.0],note:'Patrón muy bajo en hidratos con prioridad proteica; la grasa completa la energía.'},
 highprotein:{label:'💪 Alta en proteína 50–100 g',carb:[50,100],protein:[1.6,2.0],note:'Prioriza proteína dentro del objetivo energético.'},
 mediterranean:{label:'🫒 Mediterránea',carbMode:'percent',carbPct:[45,55],protein:[1.2,1.6],note:'Patrón mediterráneo; prioriza vegetales, legumbres, pescado, aceite de oliva y frutos secos.'},
 medlowcarb:{label:'🫒🥩 Mediterránea Low Carb 70–130 g',carb:[70,130],protein:[1.2,1.6],note:'Enfoque mediterráneo con reducción de hidratos.'},
 dash:{label:'🫐 DASH',carbMode:'percent',carbPct:[45,65],protein:[1.2,1.6],note:'Patrón basado en alimentos mínimamente procesados, frutas/verduras, legumbres y control de sodio.'},
 vegetarian:{label:'🌱 Vegetariana',carbMode:'percent',carbPct:[45,65],protein:[1.3,1.7],note:'Patrón vegetariano; controlar fuentes proteicas y micronutrientes.'},
 vegan:{label:'🌱 Vegana',carbMode:'percent',carbPct:[45,65],protein:[1.3,1.7],note:'Patrón vegano; prestar especial atención a B12 y otros micronutrientes.'},
 longevity:{label:'🧬 Salud a largo plazo',carbMode:'percent',carbPct:[45,60],protein:[1.3,1.6],note:'Patrón flexible centrado en calidad alimentaria y sostenibilidad.'},
 calorie:{label:'🔥 Déficit calórico',carbMode:'percent',carbPct:[35,50],protein:[1.6,1.8],note:'Estrategia energética; los hidratos se mantienen en un rango moderado y la proteína ayuda a preservar masa magra.'}
};
function planDef(pattern){return PLAN_DEFS[pattern]||PLAN_DEFS.balanced}
function planLabel(pattern){return planDef(pattern).label}
function scientificallyPreferredProteinFactor(p){const ids=getObjectives(p),pattern=p?.pattern||'balanced';if(pattern==='highprotein'||pattern==='ketohighprotein'||ids.includes('gain_muscle'))return 1.6;if(ids.includes('lose_fat')||ids.includes('recomp'))return 1.4;return 1.2}
function macroTargetsFromPlan(p,cal,weight){const d=planDef(p.pattern),w=Number(weight)||lastWeight(p.id)||70,ref=proteinReferenceWeight({...p,weight:w});const minP=Math.round(ref*d.protein[0]),maxP=Math.round(ref*d.protein[1]);const preferred=scientificallyPreferredProteinFactor(p),pGoal=p.targetProteinMode==='high'?maxP:Math.max(minP,Math.min(maxP,Math.round(ref*preferred)));let carbMin,carbMax;if(d.carbMode==='percent'){carbMin=Math.round((cal*d.carbPct[0]/100)/4);carbMax=Math.round((cal*d.carbPct[1]/100)/4)}else{carbMin=d.carb[0];carbMax=d.carb[1]}let carbs=Math.round((carbMin+carbMax)/2);const minFat=Math.max(15,Math.round(cal*.15/9));let fat=(cal-pGoal*4-carbs*4)/9;if(fat<minFat){const maxPForFat=Math.floor((cal-carbs*4-minFat*9)/4);pGoal=Math.max(minP,Math.min(pGoal,maxPForFat));fat=(cal-pGoal*4-carbs*4)/9}fat=Math.max(minFat,Math.round(fat*10)/10);return {carbs,carbMin,carbMax,protein:pGoal,proteinMin:minP,proteinMax:maxP,fat,fatMin:Math.round(minFat),fatMax:Math.round(fat*1.15)}}
function patternLabel(p){return planLabel(p?.pattern||'balanced')}
function activityLabel(a){return {sedentario:'Sedentario (poco o nada de ejercicio)',liviana:'Actividad liviana (1-3 días/semana)',moderada:'Actividad moderada (3-5 días/semana)',activa:'Activo (6-7 días/semana)',muyactiva:'Muy activo (trabajo físico o 2x/día)'}[a]||'Actividad liviana (1-3 días/semana)'}
function validateProfileInputs(d){const age=Number(d.age),height=Number(d.height),weight=Number(d.weight);const errs=[];if(!Number.isFinite(age)||age<18||age>100)errs.push('Edad fuera de rango (18–100 años). El cálculo automático usa Mifflin–St Jeor, validada en población adulta.');if(!['M','F'].includes(d.sex))errs.push('Sexo necesario para Mifflin–St Jeor.');if(!Number.isFinite(height)||height<120||height>230)errs.push('Altura fuera de rango (120–230 cm).');if(!Number.isFinite(weight)||weight<30||weight>300)errs.push('Peso fuera de rango (30–300 kg).');return errs}
function proteinReferenceWeight(d){const w=Number(d.weight),h=Number(d.height),goal=Number(d.goal);if(!Number.isFinite(w)||w<=0)return 70;let ref=Number.isFinite(goal)&&goal>0?goal:(Number.isFinite(h)&&h>0?h*h*.0001*25:w);const bmi=Number.isFinite(h)&&h>0?ref/(h*h*.0001):null;if(!Number.isFinite(bmi)||bmi<18.5||bmi>29.9)ref=Number.isFinite(h)&&h>0?h*h*.0001*25:w;return Math.round(Math.min(w,Math.max(40,ref))*10)/10}
function calcAutoTargets(d){const errs=validateProfileInputs(d);if(errs.length)return null;const age=Number(d.age),sex=d.sex,height=Number(d.height),weight=Number(d.weight),activityFactors={sedentario:1.2,liviana:1.375,moderada:1.55,activa:1.725,muyactiva:1.9};const bmr=sex==='F'?(10*weight+6.25*height-5*age-161):(10*weight+6.25*height-5*age+5);const tdee=bmr*(activityFactors[d.activity]||1.2),rawGoal=d.goalType,goalCode=['bajar','lose_fat'].includes(rawGoal)?'bajar':['subir','gain_muscle'].includes(rawGoal)?'subir':rawGoal==='recomp'?'recomp':'mantener';let cal=tdee;if(goalCode==='bajar')cal=tdee-400;else if(goalCode==='recomp')cal=tdee-200;else if(goalCode==='subir')cal=tdee+250;const floor=sex==='F'?1300:1500;cal=Math.max(floor,Math.min(4500,Math.round(cal)));const pf=d.pattern==='highprotein'||goalCode==='subir'?1.6:(goalCode==='bajar'||goalCode==='recomp'?1.4:1.2),ref=proteinReferenceWeight(d),pr=Math.round(ref*pf);return {cal,pr,bmr:Math.round(bmr),tdee:Math.round(tdee),proteinReferenceWeight:Math.round(ref),proteinFactor:pf,method:'Mifflin-St Jeor + factor de actividad',confidence:'estimación inicial',safetyNote:'El piso calórico es una salvaguarda técnica, no una prescripción médica.'}
}
function median(a){const v=a.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!v.length)return null;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2}
function trendWeightAt(date,pid){const ws=weights(pid).filter(x=>x.date<=date);if(!ws.length)return null;const recent=ws.slice(-3).map(x=>x.kg);return median(recent)}
function ewma(values,alpha=.25){let v=null;for(const x of values){if(!Number.isFinite(x))continue;v=v==null?x:alpha*x+(1-alpha)*v}return v}
function adaptiveEnergy(p,daysN=28){const ds=days(daysN),foodDays=ds.filter(d=>entriesFor(d,p.id).length>=2&&totals(d,p.id).kcal>=800),ws=weights(p.id).filter(x=>ds.includes(x.date));if(foodDays.length<14||ws.length<4)return null;const avgKcal=foodDays.reduce((a,d)=>a+totals(d,p.id).kcal,0)/foodDays.length,series=ds.map(d=>({date:d,kg:trendWeightAt(d,p.id)})).filter(x=>Number.isFinite(x.kg));if(series.length<4||!Number.isFinite(avgKcal))return null;const smoothed=ewma(series.map(x=>x.kg),.25),first=series[0].kg,deltaKg=smoothed-first,elapsed=Math.max(7,(new Date(series.at(-1).date)-new Date(series[0].date))/86400000);let expenditure=avgKcal-(7700*deltaKg/elapsed);expenditure=Math.max(1200,Math.min(4500,expenditure));const coverage=foodDays.length/ds.length,weightCoverage=series.length/ds.length,confidence=foodDays.length>=21&&series.length>=6&&coverage>=.75&&weightCoverage>=.5?'alta':foodDays.length>=17&&series.length>=4&&coverage>=.6?'moderada':'baja';return {expenditure:Math.round(expenditure),avgKcal:Math.round(avgKcal),deltaKg:+deltaKg.toFixed(2),days:Math.round(elapsed),foodDays:foodDays.length,weights:series.length,coverage:+coverage.toFixed(2),weightCoverage:+weightCoverage.toFixed(2),confidence,method:'EWMA de tendencia + balance energético'}}
function safeAdaptiveTargets(p){const a=adaptiveEnergy(p,28);return a&&a.confidence!=='baja'?a:null}
function recommendedTargets(p){const w=lastWeight(p.id)||70,op=objectiveProfile(p),base=calcAutoTargets({age:p.age,sex:p.sex,height:p.height,weight:w,goal:p.goal,activity:p.activity,goalType:objectivesToGoalCode(op.ids),pattern:p.pattern});if(!base)return {cal:p.cal||1900,pr:p.pr||120,adaptive:false,source:'sin sexo especificado',confidence:'insuficiente'};const ad=safeAdaptiveTargets(p);if(!ad)return {...base,adaptive:false,source:'Mifflin-St Jeor',confidence:adaptiveEnergy(p,28)?.confidence||'insuficiente'};let cal=ad.expenditure;if(op.mode==='fat_loss')cal-=400;else if(op.mode==='recomp')cal-=200;else if(op.mode==='muscle')cal+=200;cal=Math.max(p.sex==='F'?1300:1500,Math.min(4500,Math.round(cal)));const macro=macroTargetsFromPlan({...p,goal:p.goal,goalType:objectivesToGoalCode(op.ids)},cal,w);return {cal,pr:macro.protein,bmr:base.bmr,tdee:ad.expenditure,adaptive:true,source:'Tendencia de peso + ingesta real',confidence:ad.confidence,adaptiveData:ad,proteinReferenceWeight:proteinReferenceWeight({weight:w,goal:p.goal,goalType:objectivesToGoalCode(op.ids)})}
}
function objectivesToGoalCode(ids){if(ids.includes('recomp'))return 'recomp';if(ids.includes('lose_fat'))return 'bajar';if(ids.includes('gain_muscle'))return 'subir';return 'mantener'}
function autoFiberTarget(cal,pattern='balanced'){const base=Math.round((Number(cal)||1900)/1000*14);return Math.max(25,Math.min(50,base))}
function autoWaterTarget(weightKg,sex){return sex==='F'?2000:2500}
function targets(p){
 const w=lastWeight(p.id)||70;const auto=p.targetMode!=='manual'?recommendedTargets(p):null;const calc=calcAutoTargets({age:p.age,sex:p.sex,height:p.height,weight:w,goal:p.goal,activity:p.activity,goalType:objectivesToGoalCode(objectiveProfile(p).ids),pattern:p.pattern});
 const calBase=auto?.cal??(Number(p.cal)>0?p.cal:(calc?.cal||1900));const macro=macroTargetsFromPlan(p,calBase,w);const protein=Number(p.pr)>0&&p.targetMode==='manual'?Number(p.pr):macro.protein;const carbs=Number(p.carbs)>0&&p.targetMode==='manual'?Number(p.carbs):macro.carbs;const fat=Number(p.fat)>0&&p.targetMode==='manual'?Number(p.fat):Math.max(20,Math.round((calBase-protein*4-carbs*4)/9));
 return {cal:calBase,protein,proteinMin:macro.proteinMin,proteinMax:macro.proteinMax,carbs,carbMin:macro.carbMin,carbMax:macro.carbMax,fat,fatMin:Math.max(20,Math.round(fat*.85)),fatMax:Math.round(fat*1.15),fiber:p.targetMode==='manual'&&Number(p.fiber)>0?p.fiber:autoFiberTarget(calBase,p.pattern),sugar:null,sodium:Number(p.sodium)>0?p.sodium:2000,sat:Number(p.sat)>0?p.sat:Math.round(calBase*.10/9),veg:Number(p.veg)>0?p.veg:400,water:p.targetMode==='manual'&&Number(p.water)>0?p.water:autoWaterTarget(w,p.sex),steps:0,plants:Number(p.plants)>0?p.plants:20,plan:p.pattern||'balanced',note:planDef(p.pattern).note};
}
function targetProtein(p){return Number(targets(p).protein||120)}
function entriesFor(date=localDate(),pid=getActiveProfile()?.id){return db.entries.filter(x=>x.date===date&&x.pid===pid)}
function totals(date=localDate(),pid=getActiveProfile()?.id){const MACRO_KEYS=['kcal','p','c','f','fib','sugar','sat','sodium','veg','fruit','plantCount','wholeFoodCount','ultraCount'];const MICRO_KEYS=['calcium','iron','magnesium','potassium','vitC','vitD','vitE','b12','folate','omega3','omega6','zinc','phosphorus','iodine','cholesterol'];const t={kcal:0,p:0,c:0,f:0,fib:0,sugar:0,sat:0,sodium:0,veg:0,fruit:0,plantCount:0,wholeFoodCount:0,ultraCount:0};const microSums=Object.fromEntries(MICRO_KEYS.map(k=>[k,0])),complete=Object.fromEntries(MICRO_KEYS.map(k=>[k,true]));for(const x of entriesFor(date,pid)){for(const k of MACRO_KEYS){const v=Number(x[k]);t[k]+=(Number.isFinite(v)&&v>=0?v:0)}for(const k of MICRO_KEYS){const v=Number(x[k]);if(Number.isFinite(v)&&v>=0)microSums[k]+=v;else complete[k]=false}}const unknown=[];for(const k of MICRO_KEYS){t[k]=complete[k]?microSums[k]:undefined;if(!complete[k])unknown.push(k)}t.unknownNutrients=unknown;return t}
function weights(pid){return db.weights.filter(x=>x.pid===pid).sort((a,b)=>a.date.localeCompare(b.date))}
function lastWeight(pid){let a=weights(pid);return a.length?a[a.length-1].kg:null}
function firstWeight(pid){let a=weights(pid);return a.length?a[0].kg:null}
function days(n=7){let a=[];for(let i=n-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);a.push(localDate(d))}return a}

function calcEntryFromFood(foodName,amount,base={}){const f=allFoods()[foodName];if(!f)return null;const n=Number(String(amount).replace(',','.'));if(!Number.isFinite(n)||n<=0||n>10000)return null;const wanted=base.inputUnit||base.unitChoice||base.unit||null;let fac,grams=null,displayUnit;if(f.unitMode==='portion'){fac=n;displayUnit=f.unitLabel||'porción'}else{const opts=Array.isArray(f.unitOptions)?f.unitOptions:[{value:'g',label:'g',gramsPerUnit:1}];const u=opts.find(x=>x.value===wanted)||opts[0];const gpu=Number(u.gramsPerUnit);if(wanted&&u.value!=='g'&&(!Number.isFinite(gpu)||gpu<=0))return null;grams=n*(Number.isFinite(gpu)&&gpu>0?gpu:1);fac=grams/100;displayUnit=u.label||'g'}const out={...base,food:foodName,amount:n,unit:displayUnit,unitMode:f.unitMode,grams,qty:n,kcal:(f.kcal||0)*fac,p:(f.p||0)*fac,c:(f.c||0)*fac,f:(f.f||0)*fac,fib:(f.fib||0)*fac,sugar:(f.sugar||0)*fac,sat:(f.sat||0)*fac,sodium:(f.sodium||0)*fac,veg:(f.veg||0)*fac,fruit:(f.fruit||0)*fac,source:f.source||base.source||'Base local provisoria',sourceStatus:f.sourceStatus||'pendiente de validación',estimate:!!base.estimate,confidence:Number.isFinite(Number(base.confidence))?Number(base.confidence):(base.estimate?.5:1),unknownNutrients:[],inputUnit:wanted||f.unitLabel||'g'};NUTRIENT_FIELDS.slice(8).forEach(k=>{if(f[k]===undefined||f[k]===null||!Number.isFinite(Number(f[k])))out.unknownNutrients.push(k);else out[k]=Number(f[k])*fac});out.dataQuality=out.unknownNutrients.length?'incompleto':'provisional';const _p=Number(f.p||0),_c=Number(f.c||0),_ff=Number(f.f||0),_fib=Number(f.fib||0);const mk=4*_p+4*(_c-_fib)+2*_fib+9*_ff;const mk2=4*_p+4*_c+9*_ff;const _kcal=Number(f.kcal||0);out.energyConsistency=Number.isFinite(_kcal)&&_kcal>0?(Math.abs(mk-_kcal)/_kcal<=.10||Math.abs(mk2-_kcal)/_kcal<=.12):'sin_datos';if(f.plant)out.plantCount=1;if(f.processing==='ultra')out.ultraCount=1;if(f.processing==='whole')out.wholeFoodCount=1;return out}
