function setWaterDialog(){const p=getActiveProfile(),v=db.waterByDate[`${p.id}|${localDate()}`]||0;openModal({title:'💧 Editar agua',body:`<label>Volumen registrado hoy (ml)</label><input id="waterInput" type="number" min="0" max="10000" step="50" value="${v}"><button onclick="const n=document.getElementById('waterInput').value;closeModal();setWaterToday(n)">Guardar</button>`})}
/* formatDate — convierte 2026-09-09 → 09/09/26 */
function formatDate(dateStr){
  if(!dateStr) return '—';
  const parts = dateStr.split('-');
  if(parts.length !== 3) return dateStr;
  return parts[2] + '/' + parts[1] + '/' + parts[0].slice(2);
}

function _nfWeekStart(dateStr){const d=new Date((dateStr||localDate())+'T12:00:00');const day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return d}
function _nfWeekDates(anchor){const start=_nfWeekStart(anchor);return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return localDate(d)})}
function _nfWeekLetter(dateStr){return ['D','L','M','X','J','V','S'][new Date(dateStr+'T12:00:00').getDay()]}
function _nfDayLabel(dateStr){return ['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'][new Date(dateStr+'T12:00:00').getDay()]}
function selectedJournalDate(value=''){if(value){window.journalDate=localDate(new Date(value+'T12:00:00'));return window.journalDate}return window.journalDate||localDate()}
function selectJournalDay(date){const dates=_nfWeekDates(selectedJournalDate());if(!dates.includes(date))return;window.journalDate=date;render()}
function shiftJournalWeek(delta){const d=_nfWeekStart(selectedJournalDate());d.setDate(d.getDate()+Number(delta||0)*7);window.journalDate=localDate(d);render()}
function weeklyJournalStripHtml(selected=selectedJournalDate()){const p=getActiveProfile();const dates=_nfWeekDates(selected);return `<div class="nf-journal-top"><div class="nf-week-picker-wrap"><button class="nf-week-nav" type="button" aria-label="Semana anterior" onclick="shiftJournalWeek(-1)">‹</button><div class="nf-week-days">${dates.map(date=>{const active=date===selected,has=entriesFor(date,p.id).length>0;return `<button type="button" class="nf-week-day ${active?'selected':''} ${has?'has-data':''}" aria-label="${esc(_nfDayLabel(date))} ${esc(date)}" aria-pressed="${active}" onclick="selectJournalDay('${date}')"><span class="nf-week-letter">${_nfWeekLetter(date)}</span><span class="nf-week-circle">${Number(date.slice(-2))}</span>${has?'<i aria-hidden="true"></i>':''}</button>`}).join('')}</div><button class="nf-week-nav" type="button" aria-label="Semana siguiente" onclick="shiftJournalWeek(1)">›</button></div></div>`}
function journalDaySummaryHtml(t){return `<div class="nf-week-metrics"><div class="nf-week-metric kcal"><span>Calorías</span><b>${Math.round(t.kcal)} kcal</b></div><div class="nf-week-metric"><span>Proteína</span><b>${Math.round(t.p)} g</b></div><div class="nf-week-metric"><span>Carbohidratos</span><b>${Math.round(t.c)} g</b></div><div class="nf-week-metric"><span>Grasa</span><b>${Math.round(t.f)} g</b></div><div class="nf-week-metric"><span>Fibra</span><b>${Math.round(t.fib)} g</b></div></div>`}
function renderJournal(){
 let el=document.getElementById('journal'),p=getActiveProfile(),date=selectedJournalDate(),arr=entriesFor(date,p.id),t=totals(date,p.id),groups=groupMealEntries(arr);
 const mealCards=_nfMealTypes().map(type=>{const xs=groups[type];if(!xs.length)return `<div class="nf-journal-meal"><div class="nf-journal-meal-head"><h3>${esc(type)}</h3><span class="muted small">Sin registros</span></div></div>`;const mt=xs.reduce((a,x)=>{a.kcal+=Number(x.kcal)||0;a.p+=Number(x.p)||0;a.c+=Number(x.c)||0;a.f+=Number(x.f)||0;a.fib+=Number(x.fib)||0;return a},{kcal:0,p:0,c:0,f:0,fib:0});return `<div class="nf-journal-meal"><div class="nf-journal-meal-head"><h3>${esc(type)}</h3><b>${Math.round(mt.kcal)} kcal</b></div>${xs.map((x)=>{const idx=arr.indexOf(x);return `<div class="nf-journal-item"><div><b>${esc(foodIcon(x.food,allFoods()[x.food]))} ${esc(x.food)}</b><br><small>${esc(x.amount||x.qty||x.grams||'')} ${esc(x.unit||'g')}${x.estimate?' · estimación':''}</small></div><div class="nf-journal-item-right"><small>P ${Math.round(x.p||0)} · C ${Math.round(x.c||0)} · G ${Math.round(x.f||0)} · Fib ${Math.round(x.fib||0)} g</small><div class="nf-journal-actions"><button class="secondary small" onclick="editEntry(${idx})">Editar</button><button class="danger small" onclick="deleteEntry(${idx})">Borrar</button></div></div></div>`}).join('')}<div class="nf-journal-total"><span>Proteína <b>${Math.round(mt.p)} g</b></span><span>Carbohidratos <b>${Math.round(mt.c)} g</b></span><span>Grasas <b>${Math.round(mt.f)} g</b></span><span>Fibra <b>${Math.round(mt.fib)} g</b></span></div></div>`}).join('');
 el.innerHTML=`<div class="card nf-journal-card"><div class="nf-journal-heading"><div><h2>🍽️ Registro de comidas</h2><span class="muted small">${esc(_nfDayLabel(date))} ${esc(date)}</span></div><button class="secondary small" type="button" onclick="window.journalDate=localDate();render()">Hoy</button></div>${weeklyJournalStripHtml(date)}${journalDaySummaryHtml(t)}</div><div class="nf-journal-meals">${mealCards}</div><div class="card"><h2>⭐ Favoritos y 🕒 recientes</h2><div class="quickchips">${(db.favoriteFoods||[]).filter(x=>x.pid===p.id).map(x=>`<button class="chip" onclick="addMeal('${esc(x.food)}')">⭐ ${esc(x.food)}</button>`).join('')||'<span class="muted small">Todavía no hay favoritos.</span>'}${recentFoods(p.id,8).map(n=>`<button class="chip" onclick="addMeal('${esc(n)}')">🕒 ${esc(n)}</button>`).join('')}</div></div><div class="card"><div class="row"><h2>🥘 Mis recetas</h2><button onclick="newRecipe()">＋ Nueva</button></div>${db.recipes.length?db.recipes.map(r=>`<div class="meal"><span><b>${esc(r.name)}</b><br><small>${r.portions} porciones · ${Math.round(r.kcal/Math.max(1,Number(r.portions)||1))} kcal/porción · P ${Math.round(r.p/Math.max(1,Number(r.portions)||1))} g · G ${Math.round(r.f/Math.max(1,Number(r.portions)||1))} g</small></span><div style="display:flex;gap:6px"><button class="secondary small" onclick="useRecipe('${esc(r.id)}')">Usar</button><button class="secondary small" onclick="editRecipe('${esc(r.id)}')">Editar</button><button class="danger small" onclick="deleteRecipe('${esc(r.id)}')">Eliminar</button></div></div>`).join(''):'<div class="empty">Todavía no tenés recetas.</div>'}</div><div class="quick-actions nf-journal-quick-actions"><button onclick="addMeal()">＋ Agregar alimento</button><button class="secondary" onclick="addTextMeal()">✍️ Texto / voz</button><button class="secondary" onclick="scanBarcode()">▦ Código</button><button class="secondary" onclick="newCustomFood()">＋ Mis alimentos</button><button class="secondary" onclick="copyYesterday()">↪ Copiar ayer</button></div>`
}
function changeJournalDate(delta){const n=Number(delta);if(!Number.isInteger(n)||Math.abs(n)>30)return;let d=new Date((selectedJournalDate())+'T12:00:00');d.setDate(d.getDate()+n);window.journalDate=localDate(d);render()}

function microDisplay(t,key,unit='',scale=1,dec=0){const v=t?.[key];if(v===undefined||v===null||!Number.isFinite(Number(v)))return '—';const n=Number(v)*scale;return `${dec? n.toFixed(dec):Math.round(n)} ${unit}`}
function progressPage(){let el=document.getElementById('progress'),p=getActiveProfile(),st=weekStats(p.id),tg=targets(p),ws=weights(p.id),last=lastWeight(p.id),start=firstWeight(p.id),goal=p.goal,ad=smartAdvice(p,st),sugs=mealSuggestions(p),goalObj=objectiveProfile(p);let trend='Sin suficientes pesajes';if(ws.length>=2){let a=ws.slice(-Math.min(4,ws.length)),delta=a[a.length-1].kg-a[0].kg;trend=delta<-.2?`Tendencia descendente: ${Math.abs(delta).toFixed(1)} kg`:delta>.2?`Tendencia ascendente: ${delta.toFixed(1)} kg`:'Tendencia estable'}let goalPct=(start&&goal&&last&&start!==goal)?Math.max(0,Math.min(100,((start-last)/(start-goal))*100)):0;el.innerHTML=`<div class="card"><div class="row"><div><h2>📊 Progreso</h2><span class="pill">Últimos 7 días</span></div><span class="tag">${goalObj.mode==='recomp'?'🔄 Recomposición':patternLabel(p)}</span></div><div class="macro-grid main-macros"><div><b>${Math.round(st.avgKcal)}</b><span>kcal/día promedio</span></div><div><b>${Math.round(st.avgProtein)} g</b><span>proteína/día</span></div><div><b>${Math.round(st.avgCarbs)} g</b><span>hidratos/día</span></div><div><b>${Math.round(st.avgSteps)}</b><span>pasos/día</span></div></div><p class="muted small">Esto es un promedio de 7 días, no el consumo de hoy. Hoy: ${Math.round(totals(localDate(),p.id).kcal)} kcal.</p></div><div class="card"><h2>🔥 Gasto energético estimado</h2>${(()=>{const a=adaptiveEnergy(p,28);if(!a)return `<p class="muted">Todavía no hay suficientes datos para estimarlo. Se necesitan varios días de ingesta y pesajes.</p>`;return `<p><b>${a.expenditure} kcal/día</b></p><p class="muted small">Estimación a partir de ingesta registrada y tendencia de peso. No es una medición metabólica.</p><p>Objetivo actual: <b>${Math.round(tg.cal)} kcal/día</b></p>`})()}</div><div class="card"><h2>🧠 Análisis</h2>${ad.map(x=>`<div class="notice">• ${esc(x)}</div>`).join('')}</div><div class="card"><h2>🍽️ Sugerencias que podés agregar</h2>${sugs.length?sugs.map(x=>`<div class="suggest"><div><b>${esc(x.title)}</b><br><small>${esc(x.desc)} · ~${x.kcal} kcal · ~${x.protein} g proteína</small></div><button onclick="addSuggestion('${esc(x.food)}',${x.qty},'${esc(x.unit)}')">Agregar</button></div>`).join(''):'<div class="empty">No hay sugerencias suficientes con los datos actuales.</div>'}</div><div class="card"><h2>⚖️ Tendencia de peso</h2><div class="big">${last?last+' kg':'—'}</div><p class="muted">${trend}</p>${goal?`<div class="bar"><i style="width:${goalPct}%"></i></div><small>Avance estimado hacia ${goal} kg: ${Math.round(goalPct)}%</small>`:''}</div>`}
function showTab(tab){const allowed=['home','journal','progress','weight','profile'];if(!allowed.includes(tab))return;window._nfCurrentTab=tab;for(const id of allowed){const el=document.getElementById(id);if(el)el.classList.toggle('hidden',id!==tab)}document.querySelectorAll('.tabs button[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render();}
function render(){if(!getActiveProfile())return setup();const add=document.getElementById('addBtn');if(add)add.classList.remove('hidden');const tab=window._nfCurrentTab||'home';if(tab==='home')renderHome();else if(tab==='journal')renderJournal();else if(tab==='progress')progressPage();else if(tab==='weight')renderWeight();else profilePage();for(const id of ['home','journal','progress','weight','profile']){const el=document.getElementById(id);if(el)el.classList.toggle('hidden',id!==tab);}}

function pct(v,t){const n=Number(v),d=Number(t);return !Number.isFinite(n)||!Number.isFinite(d)||d<=0?0:Math.max(0,Math.min(100,Math.round(n/d*100)))}
function meter(label,v,t,unit='',reverse=false){const n=Number(v),target=Number(t);if(!Number.isFinite(n)||!Number.isFinite(target)||target<=0)return `<div style="margin:9px 0"><div class="row"><span>${esc(label)}</span><b>Dato no disponible</b></div></div>`;const good=reverse?n<=target:n>=target;return `<div style="margin:9px 0"><div class="row"><span>${esc(label)}</span><b>${Math.round(n*10)/10} / ${Math.round(target*10)/10} ${esc(unit)}</b></div><div class="bar"><i style="width:${pct(n,target)}%"></i></div></div>`}
function setup(){document.getElementById('home').innerHTML=`<div class="card"><h2>🥗 NutriFamilia V7.8.7</h2><p class="muted">Seguimiento familiar de peso, alimentación y hábitos. Los datos quedan en este teléfono. Los valores nutricionales locales son provisionales hasta su validación por alimento.</p><button onclick="newProfile()">+ Crear perfil</button></div>`;['journal','progress','weight','profile'].forEach(x=>{const el=document.getElementById(x);if(el)el.innerHTML=''});const add=document.getElementById('addBtn');if(add)add.classList.add('hidden')}
function addWeight(){openModal({title:'⚖️ Registrar nuevo peso',body:`<p class="muted small">El peso inicial se conserva. Cada nuevo registro queda en tu historial.</p><label>Peso actual (kg)</label><input id="wkg" type="number" min="30" max="300" step="0.1" inputmode="decimal" placeholder="Ej. 81,8"><button onclick="saveWeight()">Guardar peso</button>`})}
function saveWeight(){const kg=Number(String(document.getElementById('wkg').value||'').replace(',','.'));if(!Number.isFinite(kg)||kg<30||kg>300)return alert('Ingresá un peso entre 30 y 300 kg.');const p=getActiveProfile(),pid=p.id;const wdateEl=document.getElementById('wdate');const date=(wdateEl&&wdateEl.value)?wdateEl.value:localDate();const snapshot=JSON.parse(JSON.stringify(db.weights));const existing=db.weights.find(x=>x.pid===pid&&x.date===date);if(existing&&!existing.isInitial){existing.kg=kg;existing.source='manual';existing.recordedAt=new Date().toISOString();}else{db.weights.push({id:'w_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),pid,date,kg,source:'manual',isInitial:false,recordedAt:new Date().toISOString()});}p.weight=kg;if(!save()){db.weights=snapshot;return}closeModal();render()}
function editWeight(id){const safe=String(id||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,96);if(!safe)return;const w=db.weights.find(x=>x.pid===getActiveProfile().id&&x.id===safe);if(!w)return;if(w.isInitial||w.source==='inicio')return alert('El peso inicial se conserva como referencia y no se puede editar aquí.');openModal({title:'Editar peso',body:`<label>Peso (kg)</label><input id="ewkg" type="number" min="30" max="300" step="0.1" value="${Number(w.kg)}"><button onclick="saveEditWeight('${safe}')">Guardar</button>`})}
function saveEditWeight(id){const safe=String(id||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,96);if(!safe)return;const kg=Number(String(document.getElementById('ewkg').value||'').replace(',','.'));if(!Number.isFinite(kg)||kg<30||kg>300)return alert('Ingresá un peso entre 30 y 300 kg.');const p=getActiveProfile(),w=db.weights.find(x=>x.pid===p.id&&x.id===safe);if(!w)return;if(w.isInitial||w.source==='inicio')return alert('El peso inicial se conserva y no se puede modificar.');const old=w.kg,oldAt=w.recordedAt;w.kg=kg;w.recordedAt=new Date().toISOString();p.weight=lastWeight(p.id);if(!save()){w.kg=old;w.recordedAt=oldAt;return}closeModal();render()}
function deleteWeight(id){const safe=String(id||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,96);if(!safe)return;const p=getActiveProfile(),w=db.weights.find(x=>x.pid===p.id&&x.id===safe);if(!w)return;if(w.isInitial||w.source==='inicio')return alert('El peso inicial se conserva como referencia y no se puede eliminar.');if(!confirm('¿Eliminar este registro de peso?'))return;const snap=JSON.stringify(db.weights),old=p.weight;db.weights=db.weights.filter(x=>!(x.pid===p.id&&x.id===safe));p.weight=lastWeight(p.id);if(!save()){db.weights=JSON.parse(snap);p.weight=old;return}render()}
function changeJournalDate(delta){const n=Number(delta);if(!Number.isInteger(n)||Math.abs(n)>30)return;let d=new Date((window.journalDate||localDate())+'T12:00:00');d.setDate(d.getDate()+n);window.journalDate=localDate(d);render()}
async function lookupBarcode(raw){const code=String(raw||'').replace(/\D/g,'');if(!/^\d{8,14}$/.test(code))return openModal({title:'▦ Código',body:'<div class="notice">Código no válido.</div><button onclick="closeModal()">Cerrar</button>'});try{const ctrl=new AbortController(),tid=setTimeout(()=>ctrl.abort(),8000);let r;try{r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json',{headers:{'Accept':'application/json'},signal:ctrl.signal})}finally{clearTimeout(tid)}if(!r.ok)throw new Error('No se pudo consultar Open Food Facts.');const j=await r.json(),p=j.product;if(!p||!p.product_name)return openModal({title:'▦ Código detectado',body:`<p><b>${esc(code)}</b></p><div class="notice">No encontré una ficha pública para este código. Usá la etiqueta del envase.</div><button onclick="closeModal()">Cerrar</button>`});const n=p.nutriments||{},num=k=>Number(n[k]),vals={kcal:num('energy-kcal_100g'),p:num('proteins_100g'),c:num('carbohydrates_100g'),f:num('fat_100g'),fib:num('fiber_100g'),sugar:num('sugars_100g'),sat:num('saturated-fat_100g'),sodium:num('sodium_100g')*1000};const food={name:String(p.product_name).slice(0,120),...Object.fromEntries(Object.entries(vals).map(([k,v])=>[k,Number.isFinite(v)?v:undefined])),unitMode:'per100g',unitLabel:'g',basis:'por 100 g según etiqueta/base del producto',source:'Open Food Facts / etiqueta del producto',sourceStatus:'Dato de producto: verificar contra el envase; no sustituye una fuente científica de composición',barcode:code};db.customFoods=db.customFoods||[];const barcodeOld=db.customFoods.slice();db.customFoods=db.customFoods.filter(x=>x.name!==food.name);if(db.customFoods.length>=500){db.customFoods=barcodeOld;return openModal({title:'▦ Límite de alimentos',body:'<div class="notice">Llegaste al límite de 500 alimentos personalizados. Eliminá alguno antes de guardar otro producto.</div><button onclick="closeModal()">Cerrar</button>'})}db.customFoods.push(food);if(!save()){db.customFoods.pop();return}openModal({title:'▦ Producto encontrado',body:`<p><b>${esc(food.name)}</b></p><div class="notice">Se guardó como alimento de producto. Verificá la etiqueta antes de usarlo como referencia científica.</div><p>${Number.isFinite(food.kcal)?Math.round(food.kcal):'—'} kcal · P ${Number.isFinite(food.p)?Math.round(food.p*10)/10:'—'} g · C ${Number.isFinite(food.c)?Math.round(food.c*10)/10:'—'} g · G ${Number.isFinite(food.f)?Math.round(food.f*10)/10:'—'} g / 100 g</p><button onclick="closeModal();addMeal('${esc(food.name)}')">Agregar alimento</button>`})}catch(e){const msg=e&&e.name==='AbortError'?'La consulta tardó demasiado. Verificá tu conexión o registrá el alimento manualmente.':(e.message||e);openModal({title:'▦ Producto no disponible',body:`<div class="notice">${esc(msg)}<br>La búsqueda es opcional y requiere conexión.</div><button onclick="closeModal()">Cerrar</button>`})}}
async function scanBarcode(){if(!('BarcodeDetector' in window)){return openModal({title:'▦ Código de barras',body:'<div class="notice">Este navegador no ofrece BarcodeDetector.</div><button onclick="closeModal()">Cerrar</button>'})}if(!navigator.mediaDevices?.getUserMedia)return openModal({title:'▦ Código de barras',body:'<div class="notice">La cámara no está disponible en este contexto.</div><button onclick="closeModal()">Cerrar</button>'});openModal({title:'▦ Código de barras',body:'<p class="muted small">Apuntá la cámara al código.</p><video id="barcodeVideo" autoplay playsinline style="width:100%;border-radius:14px"></video><div id="barcodeStatus" class="notice">Inicializando cámara…</div><button class="secondary" onclick="stopBarcode()">Cerrar</button>'});try{const v=document.getElementById('barcodeVideo');window._barcodeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});v.srcObject=window._barcodeStream;const det=new BarcodeDetector();const tick=async()=>{if(!document.getElementById('barcodeVideo'))return;try{const codes=await det.detect(v);if(codes.length){const raw=String(codes[0].rawValue||'');stopBarcode();await lookupBarcode(raw);return}}catch(_){}requestAnimationFrame(tick)};tick()}catch(e){stopBarcode();openModal({title:'▦ No disponible',body:`<div class="notice">${esc(e.message||e)}</div><button onclick="closeModal()">Cerrar</button>`})}}
function stopBarcode(){if(window._barcodeStream){window._barcodeStream.getTracks().forEach(t=>t.stop());window._barcodeStream=null}closeModal()}
function analyzePhoto(file){if(!file)return;if(!aiConfigured())return alert('Configurá NutriIA antes de analizar fotos.');const reader=new FileReader();reader.onload=async()=>{try{openModal({title:'📷 Analizando foto…',body:'<div class="empty">Identificando alimentos y cantidades aproximadas…</div>'});const prompt='Analizá esta foto de comida. Devolvé SOLO JSON válido: {"items":[{"name":"nombre simple del alimento","grams":100,"unit":"g","confidence":0.8}],"meal_type":"Almuerzo","notes":""}. No inventes ingredientes ocultos. Si una cantidad no puede estimarse razonablemente, usá confidence baja.';const raw=await callAI(prompt,reader.result);const json=JSON.parse(raw.replace(/```json|```/g,'').trim());if(!Array.isArray(json.items))throw new Error('La IA no devolvió alimentos válidos.');json.items=json.items.map(x=>({...x,confidence:Math.min(1,Math.max(0,Number(x.confidence)||0.4))}));showAIResult(json,'Foto de comida')}catch(e){openModal({title:'📷 No pude analizar',body:`<div class="notice">${esc(e.message)}</div><button onclick="closeModal()">Cerrar</button>`})}};reader.readAsDataURL(file)}
